# Generated by Django 3.1.5 on 2021-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='subject',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
